# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AlboCbZ_Jl8BLX92v-kdp1VC_BgcflNn
"""

# Step 1: Import Required Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

# Step 2: Load the Dataset
# df = pd.read_csv("Housing.csv")  # Update path if needed
print("First 5 rows of the dataset:")
print(df.head())

# Step 3: Check Columns and Clean Data
print("\nDataset Columns:")
print(df.columns)

# Rename columns if needed (optional)
# df.rename(columns={'area': 'square_feet', 'bedrooms': 'bedrooms', 'bathrooms': 'bathrooms', 'price': 'price'}, inplace=True)

# Step 4: Check for Null Values
print("\nMissing Values:")
print(df.isnull().sum())

# Step 5: Select Features and Target Variable
# Update column names here to match your dataset
X = df[['square_feet', 'bedrooms', 'bathrooms']]  # Independent variables
y = df['price']  # Target variable

# Step 6: Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 7: Build and Train the Linear Regression Model
model = LinearRegression()
model.fit(X_train, y_train)

# Step 8: Make Predictions
y_pred = model.predict(X_test)

# Step 9: Evaluate the Model
print("\nModel Evaluation:")
print("R² Score:", r2_score(y_test, y_pred))
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))

# Step 10: Visualization – Actual vs Predicted
plt.figure(figsize=(8, 5))
plt.scatter(y_test, y_pred, color='blue')
plt.plot([y.min(), y.max()], [y.min(), y.max()], 'r--')  # Ideal line
plt.xlabel("Actual Prices")
plt.ylabel("Predicted Prices")
plt.title("Actual vs Predicted House Prices")
plt.grid(True)
plt.show()

# Step 11: Show Coefficients
print("\nModel Coefficients:")
print("Intercept:", model.intercept_)
print("Coefficients (for area, bedrooms, bathrooms):", model.coef_)

# Step 12: Predict Price for a New House
new_data = pd.DataFrame({
    'square_feet': [2500],
    'bedrooms': [4],
    'bathrooms': [3]
})
predicted_price = model.predict(new_data)
print("\nPredicted price for 2500 sqft, 4 bed, 3 bath:", predicted_price[0])